---
- name: Install Apache
  apt:
    name: apache2

- name: Get Apache version
  shell: "dpkg -l | awk '$2 ~ /^apache2$/ {print $3}' | awk -F- '{print $1}'"
  register: _apache_version

- name: Set Apache major version variable
  set_fact:
    apache_version_major: "{{ _apache_version.stdout.split('.')[0] }}"

- name: Set Apache minor version variable
  set_fact:
    apache_version_minor: "{{ _apache_version.stdout.split('.')[1] }}"

- name: Set Apache patch version variable
  set_fact:
    apache_version_patch: "{{ _apache_version.stdout.split('.')[2] }}"

- name: Disable Apache modules
  apache2_module:
    name: "{{ item.name }}"
    state: absent
  when: item.state | default('present') == 'absent'
  loop: "{{ apache_modules }}"
  notify: restart apache

- name: Enable Apache modules
  apache2_module:
    name: "{{ item.name }}"
  when: item.state | default('present') != 'absent'
  loop: "{{ apache_modules }}"
  notify: restart apache

- name: Add Apache virtual host for sites
- name: Ensure Apache headers module is enabled
  apache2_module:
    name: headers
  when: apache_enable_ssl_hsts or (apache_headers | length > 0)
  notify: restart apache

  template:
    src: templates/vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ item.hostname }}.conf"
  loop: "{{ apache_vhosts }}"
  notify: restart apache

- name: Enable sites
  command: "a2ensite {{ item.hostname }}.conf"
  args:
    creates: "/etc/apache2/sites-enabled/{{ item.hostname }}.conf"
  loop: "{{ apache_vhosts }}"

- name: Disbale default virtual host
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache

- name: Ensure Apache is started and enabled on boot
  service:
    name: apache2
    state: started
    enabled: yes
