---
# Variable configuration.
- include_tasks: variables.yml

# Install Apache.
- include_tasks: install.yml

# Configure Apache.
- include_tasks: configure.yml

# Add/Remove sites.
- include_tasks: add-remove-sites.yml

- name: Ensure Apache is started and enabled on boot
  service:
    name: apache2
    state: started
    enabled: yes
